<a href="https://colab.research.google.com/github/ArjunJadhav-data/Data_Science/blob/main/couunty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import pyspark as ps

In [9]:
data = pd.read_excel('/content/Sales Data Set for Dashboard.xlsx')

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

In [10]:
data.head()

       Unnamed: 0          Unnamed: 1  Unnamed: 2  dashboard
0             NaN                 NaN         NaN        NaN
1      Row Labels  Count of Ship Mode         NaN        NaN
2  Delivery Truck                 275         NaN        NaN
3     Express Air                 240         NaN        NaN
4     Regular Air                1437         NaN        NaN

In [11]:
data=pd.read_csv('/content/country.csv')

In [12]:
data.head(12)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,07-01-2015,08-01-2015,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,13-06-2015,15-06-2015,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,15-02-2015,17-02-2015,-53.8096,22,211.15,90192
3,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,12-05-2015,14-05-2015,803.4705,16,1164.45,86838
4,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,12-05-2015,13-05-2015,-24.0300,7,22.23,86838
5,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,12-05-2015,13-05-2015,-37.0300,4,13.99,86838
6,24848,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,12-05-2015,13-05-2015,-0.7100,4,14.26,86838
7,18181,Critical,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,08-04-2015,09-04-2015,-59.8200,7,33.47,86837
8,20925,Medium,0.01,35.94,6.66,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,11787,28-05-2015,28-05-2015,261.8757,10,379.53,86839
9,26267,High,0.04,2.98,1.58,16,Sarah Ramsey,Regular Air,Small Business,Office Supplies,...,East,New York,Syracuse,13210,12-02-2015,15-02-2015,2.6300,6,18.80,86836
10,26268,High,0.05,115.99,2.50,16,Sarah Ramsey,Regular Air,Small Business,Technology,...,East,New York,Syracuse,13210,12-02-2015,14-02-2015,652.7331,10,945.99,86836
11,23890,High,0.05,26.48,6.93,18,Laurie Hanna,Regular Air,Small Business,Furniture,...,West,Montana,Helena,59601,15-05-2015,16-05-2015,314.4813,17,455.77,90031

In [16]:
data[['Country','Profit']]

            Country     Profit
0     United States     4.5600
1     United States  4390.3665
2     United States   -53.8096
3     United States   803.4705
4     United States   -24.0300
...             ...        ...
1947  United States  -116.7600
1948  United States  -160.9520
1949  United States   -41.8700
1950  United States   -24.7104
1951  United States   349.4850

[1952 rows x 2 columns]

In [17]:
data['Profit']>0

0        True
1        True
2       False
3        True
4       False
        ...
1947    False
1948    False
1949    False
1950    False
1951     True
Name: Profit, Length: 1952, dtype: bool

In [27]:
data.describe()

count      1.0
mean     996.0
std        NaN
min      996.0
25%      996.0
50%      996.0
75%      996.0
max      996.0
Name: count, dtype: float64

In [28]:
data.head(13)

Profit
True    996
Name: count, dtype: int64

In [30]:
data.info()

<class 'pandas.core.series.Series'>
Index: 1 entries, True to True
Series name: count
Non-Null Count  Dtype
--------------  -----
1 non-null      int64
dtypes: int64(1)
memory usage: 9.0 bytes